//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BookDBModel", "FK_ImageBook_Infor", "Infor", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(RestService.Infor), "ImageBook", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RestService.ImageBook), true)]
[assembly: EdmRelationshipAttribute("BookDBModel", "FK_Review_Review", "Infor", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(RestService.Infor), "Review", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RestService.Review), true)]
[assembly: EdmRelationshipAttribute("BookDBModel", "FK_VideoBook_Infor", "Infor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RestService.Infor), "VideoBook", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RestService.VideoBook), true)]

#endregion

namespace RestService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BookDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BookDBEntities object using the connection string found in the 'BookDBEntities' section of the application configuration file.
        /// </summary>
        public BookDBEntities() : base("name=BookDBEntities", "BookDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BookDBEntities object.
        /// </summary>
        public BookDBEntities(string connectionString) : base(connectionString, "BookDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BookDBEntities object.
        /// </summary>
        public BookDBEntities(EntityConnection connection) : base(connection, "BookDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ImageBook> ImageBooks
        {
            get
            {
                if ((_ImageBooks == null))
                {
                    _ImageBooks = base.CreateObjectSet<ImageBook>("ImageBooks");
                }
                return _ImageBooks;
            }
        }
        private ObjectSet<ImageBook> _ImageBooks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Infor> Infors
        {
            get
            {
                if ((_Infors == null))
                {
                    _Infors = base.CreateObjectSet<Infor>("Infors");
                }
                return _Infors;
            }
        }
        private ObjectSet<Infor> _Infors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Review> Reviews
        {
            get
            {
                if ((_Reviews == null))
                {
                    _Reviews = base.CreateObjectSet<Review>("Reviews");
                }
                return _Reviews;
            }
        }
        private ObjectSet<Review> _Reviews;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VideoBook> VideoBooks
        {
            get
            {
                if ((_VideoBooks == null))
                {
                    _VideoBooks = base.CreateObjectSet<VideoBook>("VideoBooks");
                }
                return _VideoBooks;
            }
        }
        private ObjectSet<VideoBook> _VideoBooks;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ImageBooks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToImageBooks(ImageBook imageBook)
        {
            base.AddObject("ImageBooks", imageBook);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Infors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInfors(Infor infor)
        {
            base.AddObject("Infors", infor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reviews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReviews(Review review)
        {
            base.AddObject("Reviews", review);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VideoBooks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVideoBooks(VideoBook videoBook)
        {
            base.AddObject("VideoBooks", videoBook);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BookDBModel", Name="ImageBook")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ImageBook : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ImageBook object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static ImageBook CreateImageBook(global::System.Int32 id)
        {
            ImageBook imageBook = new ImageBook();
            imageBook.ID = id;
            return imageBook;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BookID
        {
            get
            {
                return _BookID;
            }
            set
            {
                OnBookIDChanging(value);
                ReportPropertyChanging("BookID");
                _BookID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BookID");
                OnBookIDChanged();
            }
        }
        private Nullable<global::System.Int32> _BookID;
        partial void OnBookIDChanging(Nullable<global::System.Int32> value);
        partial void OnBookIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BookDBModel", "FK_ImageBook_Infor", "Infor")]
        public Infor Infor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Infor>("BookDBModel.FK_ImageBook_Infor", "Infor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Infor>("BookDBModel.FK_ImageBook_Infor", "Infor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Infor> InforReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Infor>("BookDBModel.FK_ImageBook_Infor", "Infor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Infor>("BookDBModel.FK_ImageBook_Infor", "Infor", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BookDBModel", Name="Infor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Infor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Infor object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        public static Infor CreateInfor(global::System.Int32 id, global::System.Int32 type)
        {
            Infor infor = new Infor();
            infor.ID = id;
            infor.Type = type;
            return infor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field1
        {
            get
            {
                return _Field1;
            }
            set
            {
                OnField1Changing(value);
                ReportPropertyChanging("Field1");
                _Field1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field1");
                OnField1Changed();
            }
        }
        private global::System.String _Field1;
        partial void OnField1Changing(global::System.String value);
        partial void OnField1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field2
        {
            get
            {
                return _Field2;
            }
            set
            {
                OnField2Changing(value);
                ReportPropertyChanging("Field2");
                _Field2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field2");
                OnField2Changed();
            }
        }
        private global::System.String _Field2;
        partial void OnField2Changing(global::System.String value);
        partial void OnField2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field3
        {
            get
            {
                return _Field3;
            }
            set
            {
                OnField3Changing(value);
                ReportPropertyChanging("Field3");
                _Field3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field3");
                OnField3Changed();
            }
        }
        private global::System.String _Field3;
        partial void OnField3Changing(global::System.String value);
        partial void OnField3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field4
        {
            get
            {
                return _Field4;
            }
            set
            {
                OnField4Changing(value);
                ReportPropertyChanging("Field4");
                _Field4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field4");
                OnField4Changed();
            }
        }
        private global::System.String _Field4;
        partial void OnField4Changing(global::System.String value);
        partial void OnField4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field5
        {
            get
            {
                return _Field5;
            }
            set
            {
                OnField5Changing(value);
                ReportPropertyChanging("Field5");
                _Field5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field5");
                OnField5Changed();
            }
        }
        private global::System.String _Field5;
        partial void OnField5Changing(global::System.String value);
        partial void OnField5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field6
        {
            get
            {
                return _Field6;
            }
            set
            {
                OnField6Changing(value);
                ReportPropertyChanging("Field6");
                _Field6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field6");
                OnField6Changed();
            }
        }
        private global::System.String _Field6;
        partial void OnField6Changing(global::System.String value);
        partial void OnField6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field7
        {
            get
            {
                return _Field7;
            }
            set
            {
                OnField7Changing(value);
                ReportPropertyChanging("Field7");
                _Field7 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field7");
                OnField7Changed();
            }
        }
        private global::System.String _Field7;
        partial void OnField7Changing(global::System.String value);
        partial void OnField7Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field8
        {
            get
            {
                return _Field8;
            }
            set
            {
                OnField8Changing(value);
                ReportPropertyChanging("Field8");
                _Field8 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field8");
                OnField8Changed();
            }
        }
        private global::System.String _Field8;
        partial void OnField8Changing(global::System.String value);
        partial void OnField8Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.Int32 _Type;
        partial void OnTypeChanging(global::System.Int32 value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field9
        {
            get
            {
                return _Field9;
            }
            set
            {
                OnField9Changing(value);
                ReportPropertyChanging("Field9");
                _Field9 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field9");
                OnField9Changed();
            }
        }
        private global::System.String _Field9;
        partial void OnField9Changing(global::System.String value);
        partial void OnField9Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field10
        {
            get
            {
                return _Field10;
            }
            set
            {
                OnField10Changing(value);
                ReportPropertyChanging("Field10");
                _Field10 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field10");
                OnField10Changed();
            }
        }
        private global::System.String _Field10;
        partial void OnField10Changing(global::System.String value);
        partial void OnField10Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field11
        {
            get
            {
                return _Field11;
            }
            set
            {
                OnField11Changing(value);
                ReportPropertyChanging("Field11");
                _Field11 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field11");
                OnField11Changed();
            }
        }
        private global::System.String _Field11;
        partial void OnField11Changing(global::System.String value);
        partial void OnField11Changed();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BookDBModel", "FK_ImageBook_Infor", "ImageBook")]
        public EntityCollection<ImageBook> ImageBooks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ImageBook>("BookDBModel.FK_ImageBook_Infor", "ImageBook");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ImageBook>("BookDBModel.FK_ImageBook_Infor", "ImageBook", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BookDBModel", "FK_Review_Review", "Review")]
        public EntityCollection<Review> Reviews
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Review>("BookDBModel.FK_Review_Review", "Review");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Review>("BookDBModel.FK_Review_Review", "Review", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BookDBModel", "FK_VideoBook_Infor", "VideoBook")]
        public EntityCollection<VideoBook> VideoBooks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VideoBook>("BookDBModel.FK_VideoBook_Infor", "VideoBook");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VideoBook>("BookDBModel.FK_VideoBook_Infor", "VideoBook", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BookDBModel", Name="Review")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Review : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Review object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Review CreateReview(global::System.Int32 id)
        {
            Review review = new Review();
            review.ID = id;
            return review;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDInfor
        {
            get
            {
                return _IDInfor;
            }
            set
            {
                OnIDInforChanging(value);
                ReportPropertyChanging("IDInfor");
                _IDInfor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDInfor");
                OnIDInforChanged();
            }
        }
        private Nullable<global::System.Int32> _IDInfor;
        partial void OnIDInforChanging(Nullable<global::System.Int32> value);
        partial void OnIDInforChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BookDBModel", "FK_Review_Review", "Infor")]
        public Infor Infor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Infor>("BookDBModel.FK_Review_Review", "Infor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Infor>("BookDBModel.FK_Review_Review", "Infor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Infor> InforReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Infor>("BookDBModel.FK_Review_Review", "Infor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Infor>("BookDBModel.FK_Review_Review", "Infor", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BookDBModel", Name="VideoBook")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VideoBook : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VideoBook object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="bookID">Initial value of the BookID property.</param>
        public static VideoBook CreateVideoBook(global::System.Int32 id, global::System.Int32 bookID)
        {
            VideoBook videoBook = new VideoBook();
            videoBook.ID = id;
            videoBook.BookID = bookID;
            return videoBook;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BookID
        {
            get
            {
                return _BookID;
            }
            set
            {
                OnBookIDChanging(value);
                ReportPropertyChanging("BookID");
                _BookID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BookID");
                OnBookIDChanged();
            }
        }
        private global::System.Int32 _BookID;
        partial void OnBookIDChanging(global::System.Int32 value);
        partial void OnBookIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BookDBModel", "FK_VideoBook_Infor", "Infor")]
        public Infor Infor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Infor>("BookDBModel.FK_VideoBook_Infor", "Infor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Infor>("BookDBModel.FK_VideoBook_Infor", "Infor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Infor> InforReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Infor>("BookDBModel.FK_VideoBook_Infor", "Infor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Infor>("BookDBModel.FK_VideoBook_Infor", "Infor", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
